var girl = "Aisha";
console.log("girl== Aisha, This is true");
console.log(girl == "Aisha");
console.log("girl!==Aisha, This is false");
console.log(girl != "Aisha");
var car = "AudiOOOO";
console.log("car!=Mercedes, This is true");
console.log(car != "Mercedes");
console.log("car==Mercedes, This is false");
console.log(car == "Mercedes");
var fruit = "Strawberry";
console.log("fruit==Strawberry, this is true");
console.log(fruit == "Strawberry");
console.log("fruit==Apple, this is false");
console.log(fruit == "Apple");
var marks = 98;
console.log("marks>=98, this is true");
console.log(marks >= 98);
console.log("marks<98, this is false");
console.log(marks < 98);
var currency = "dollar";
console.log("currency==(dollar), it is true");
console.log(currency == "dollar");
console.log("currency==(rupee), it is false");
console.log(currency == ("rupee"));
